name: Analyze Microbat Test Report

on: [push]
    
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
  check_java_file_change:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: main
      id: main
      run: |
        if git diff --name-only HEAD HEAD^1 | grep '^microbat/.*\.java$'
        then
          echo "changed=1" >> $GITHUB_OUTPUT
        fi
    - name: ensure_report_updated
      id: finalize
      run: |
        if [ -f "test_report/report.xml" ]; then
          if git diff --name-only HEAD HEAD^1 | grep '^test_report/report.xml$'
          then
            echo "should_proceed=1" >> $GITHUB_OUTPUT
          fi
        else
          echo "test_report/report.xml does not exist"
          exit 1
        fi
    - name: die
      id: die
      if : ${{ steps.main.outputs.changed }} == '1' && ${{ steps.finalize.outputs.should_proceed }} != '1'
      run: |
        echo "You have changed java files but not updated test report. Please run test locally and update the test report."
        exit 1
    outputs:
      should_proceed: ${{ steps.finalize.outputs.should_proceed }}
  run_script:
    runs-on: ubuntu-latest
    needs: [setup_env, check_java_file_change]
    if: needs.check_java_file_change.outputs.should_proceed == '1' 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Run Scripts
      run: python3 test_report/ci.py
  