name: Analyze Microbat Test Report

on: [pull_request]
    
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
  check_java_file_change:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: main
      id: main
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^microbat/.*\.java$'
        then
          echo "changed=1" >> $GITHUB_OUTPUT
        fi
    - name: ensure_report_updated
      id: finalize
      if: steps.main.outputs.changed == '1'
      run: |
        if [ -f "test_report/report.xml" ]; then
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^test_report/report.xml$'
          then
            echo "Report is also updated"
            echo "should_proceed=1" >> $GITHUB_OUTPUT
          else
            echo "Java file updated but report is not updated"
            exit 1
        else
          echo "test_report/report.xml does not exist"
          exit 1
        fi
    outputs:
      should_proceed: ${{ steps.finalize.outputs.should_proceed }}
  run_script:
    runs-on: ubuntu-latest
    needs: [setup_env, check_java_file_change]
    if: needs.check_java_file_change.outputs.should_proceed == '1' 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Run Scripts
      run: python3 test_report/ci.py
  