name: Analyze Microbat Test Report

on: [push, pull_request]
    
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
  check_java_file_and_report_change:
    runs-on: ubuntu-latest
    env:
      REPO_FETCH_DEPTH: ${{ github.event_name == 'push' && 2 || 0 }}
      HEAD: ${{ github.event.after }}
      BASE: ${{ github.event.before }}
      
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: ${{ env.REPO_FETCH_DEPTH }}
    - name: check_java_files
      id: check_java_files
      run: |
        if git diff --name-only ${{ env.BASE }} ${{ env.HEAD }} | grep '^microbat/.*\.java$'
        then
          echo "java files changed"
          echo "changed=1" >> $GITHUB_OUTPUT
        else
          echo "java files not changed"
          echo "changed=0" >> $GITHUB_OUTPUT
        fi
    - name: ensure_report_updated
      id: check_report
      run: |
        if [ -f "test_report/report.xml" ]; then
          if git diff --name-only ${{ env.BASE }} ${{ env.HEAD }} | grep '^test_report/report.xml$'
          then
            echo "test_report/report.xml changed, should proceed"
            echo "should_proceed=1" >> $GITHUB_OUTPUT
          else
            echo "test_report/report.xml does not changed"
            echo "should_proceed=0" >> $GITHUB_OUTPUT
          fi
        else
          echo "test_report/report.xml does not exist"
          exit 1
        fi
    - name: die
      id: die
      if : ${{ steps.check_java_files.outputs.changed == '1' && steps.check_report.outputs.should_proceed != '1' }}
      run: |
        echo "You have changed java files but not updated test report. Please run test locally and update the test report."
        exit 1
    outputs:
      should_proceed: ${{ steps.check_report.outputs.should_proceed }}
  run_script:
    runs-on: ubuntu-latest
    needs: [setup_env, check_java_file_and_report_change]
    if: needs.check_java_file_and_report_change.outputs.should_proceed == '1' 
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Run Scripts
      run: python3 test_report/ci.py
  