name: Analyze Microbat Test Report

on: [pull_request]
    
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
  check_java_file_change:
    runs-on: ubuntu-latest
    steps:
      - name: main
        id: main
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^some_directory/.*\.java$'
          then
            echo "changed=1" >> $GITHUB_OUTPUT
          fi
    outputs:
      changed: ${{ steps.main.outputs.changed }}
  run_script:
    runs-on: ubuntu-latest
    needs: [setup_env, check_java_file_change]
    if: needs.check_java_file_change.outputs.changed == '1' 
    steps:
    - name: Run Scripts
      run: python3 test_report/ci.py
  